#!/usr/bin/env bash
# Builds every trainer in _src/ into a standalone page in this folder:
#   _src/<name>.src.html  +  _kit/trainer-kit.css  +  _kit/trainer-kit.js   →   <name>.html
# The shared kit is inlined, so each generated .html works on its own (no shared files at runtime).
# Run from Git Bash or WSL:   ./build.sh
set -euo pipefail
cd "$(dirname "$0")"

for src in _src/*.src.html; do
  name=$(basename "$src" .src.html)
  out="$name.html"
  awk -v css="_kit/trainer-kit.css" -v js="_kit/trainer-kit.js" -v src="$src" '
    NR == 1 { print; print "<!-- GENERATED by build.sh from " src " and _kit/. Edit those files, then run ./build.sh. -->"; next }
    /<!-- @kit:css -->/ { print "<style>"; while ((getline line < css) > 0) print line; close(css); print "</style>"; next }
    /<!-- @kit:js -->/  { print "<script>"; while ((getline line < js) > 0) print line; close(js); print "</script>"; next }
    { print }
  ' "$src" > "$out"
  echo "built $out"
done
